export const weather_code = {
    0: 'Cerah',
    1: 'Cerah Berawan',
    2: 'Cerah Berawan',
    3: 'Berawan',
    4: 'Berawan Tebal',
    5: 'Udara Kabur',
    10: 'Asap',
    45: 'Kabut',
    60: 'Hujan Ringan',
    61: 'Hujan Sedang',
    63: 'Hujan Lebat',
    80: 'Hujan Lokal',
    95: 'Hujan Petir',
    97: 'Hujan Petir',
}

export const weather_parsed = {
    'Cerah': 0,
    'Cerah Berawan': 1,
    'Cerah berawan': 1,
    'Cerah - berawan': 1,
    'Cerah Berawan': 2,
    'Berawan': 3,
    'Berawan Tebal': 4,
    'Berawan tebal': 4,
    'Udara Kabur': 5,
    'Udara kabur': 5,
    'Asap': 10,
    'Kabut': 45,
    'Hujan ringan': 60,
    'Hujan Ringan': 60,
    'Hujan Sedang': 61,
    'Hujan sedang': 61,
    'Hujan Lebat': 63,
    'Hujan lebat': 63,
    'Hujan Lokal': 80,
    'Hujan lokal': 80,
    'Hujan Petir': 95,
    'Hujan petir': 95,
    'Hujan Petir': 95,
    'Guntur': 95,
    'Guntur di sekitarnya': 95,
    'Guntur dan hujan ringan': 80
}

export const weather_video = {
    0: ''
}

export const dirTo = {
    N: 0,
    NNE: 22.5,
    NE: 45,
    ENE: 67.5,
    E: 90,
    ESE: 112.5,
    SE: 135,
    SSE: 157.5,
    S: 180,
    SSW: 202.5,
    SW: 225,
    WSW: 247.5,
    W: 270,
    WNW: 292.5,
    NW: 315,
    NNW: 337.5,
}
export const parseNameDir = {
    N: 'Utara',
    NNE: 'Utara Timur Laut',
    NE: 'Timur Laut',
    ENE: 'Timur',
    E: 'Tenggara',
    ESE: 'Selatan Timur',
    SE: 'Selatan',
    SSE: 'Selatan Barat',
    S: 'Barat',
    SSW: 'Barat Daya',
    SW: 'Barat Laut',
    WSW: 'Barat Barat',
    W: 'Barat Laut',
    WNW: 'Barat Barat',
    NW: 'Barat Utara',
    NNW: 'Utara Barat',
}