export const weather_code = {
    0: 'Bright',
    1: 'Bright Cloudy',
    2: 'Bright Cloudy',
    3: 'Cloudy',
    4: 'Thick Cloudy',
    5: 'Blurred air',
    10: 'Smoke',
    45: 'Fog',
    60: 'Light Rain',
    61: 'Moderate Rain',
    63: 'Heavy Rain',
    80: 'Local Rain',
    95: 'Thunderstorm',
    97: 'Thunderstorm',
}
export const dirTo = {
    N: 0,
    NNE: 22.5,
    NE: 45,
    ENE: 67.5,
    E: 90,
    ESE: 112.5,
    SE: 135,
    SSE: 157.5,
    S: 180,
    SSW: 202.5,
    SW: 225,
    WSW: 247.5,
    W: 270,
    WNW: 292.5,
    NW: 315,
    NNW: 337.5,
}
export const parseNameDir = {
    N: 'Utara',
    NNE: 'Utara Timur Laut',
    NE: 'Timur Laut',
    ENE: 'Timur',
    E: 'Tenggara',
    ESE: 'Selatan Timur',
    SE: 'Selatan',
    SSE: 'Selatan Barat',
    S: 'Barat',
    SSW: 'Barat Daya',
    SW: 'Barat Laut',
    WSW: 'Barat Barat',
    W: 'Barat Laut',
    WNW: 'Barat Barat',
    NW: 'Barat Utara',
    NNW: 'Utara Barat',
}